#채팅에 금액을 입력받을 NPC를 설정합니다.
NPC 설정: test

#확률을 입력합니다
#확률은 백분율로 입력합니다
#ex : 0.6 -> 60% / 0.25 -> 25% / 0.05 -> 5%
probability:
  1: 0.6
  2: 0.5
  3: 0.5
  4: 0.5
  5: 0.25
  6: 0.15
  7: 0.2
  8: 0.3
  9: 0.05
  10: 0.02

#나타낼 배율을 입력합니다 1번 배율이 -3일 경우 나올 확률은 probability의 1번입니다.
#ex : multiple 1 : -3 probability : 50% (-3 : 50%)
#곱을 나타낼 경우 'X'를 사용 해주세요. 나머지는 동일 합니다 (- , +)
#ex : X10, X50
multiple:
  1: 'X0'
  2: 'X1'
  3: '+1'
  4: '-1'
  5: 'X2'
  6: 'X3'
  7: '+2'
  8: '-3'
  9: 'X10'
  10: 'X50'
